#!/bin/bash

bribe=20000

if [ `whoami` = "root" ]
then
 echo "You are the superuser"
elif [ "$USER" = "root" ]
then
 echo "You might be the superuser"
elif [ "$bribe" -gt 10000 ]
then
 echo "You can pay to be the superuser"
else
 echo "You are still a mere mortal"
fi
